pipeline {
    agent any
    environment {
        AWS_ACCOUNT_ID="917734380283"
        AWS_DEFAULT_REGION="ap-southeast-1" 
	CLUSTER_NAME="node-cluster"
	SERVICE_NAME="sample-app-service"
	TASK_DEFINITION_NAME="first-run-task-definition:2"
	DESIRED_COUNT="1"
        IMAGE_REPO_NAME="nodejs-repo"
        IMAGE_TAG="${env.BUILD_ID}"
        REPOSITORY_URI = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}"
	registryCredential = "nodejs-cred"
    }
   
   tools {
     nodejs 'nodejs'
   }	
	
    stages {

    // Tests
    stage('Unit Tests') {
      steps{
         dir("${env.WORKSPACE}/jayesh2") {
          script {
          sh 'npm install -g'
	  sh 'npm test'
        }
		 
    }
        
      }
    }
        
    // Building Docker images
    stage('Building image') {
      steps{
        script {
          dockerImage = docker.build "${IMAGE_REPO_NAME}:${IMAGE_TAG}"
        }
      }
    }
   
    // Uploading Docker images into AWS ECR
    stage('Pushing to ECR') {
     steps{  
         script {
			docker.withRegistry("https://" + REPOSITORY_URI, "ecr:${AWS_DEFAULT_REGION}:" + registryCredential) {
                    	dockerImage.push()
                	}
         }
        }
      }
      
    stage('Deploy') {
     steps{
            withAWS(credentials: registryCredential, region: "${AWS_DEFAULT_REGION}") {
                script {
			sh './script.sh'
                }
            } 
        }
      }      
      
    }
}

